package(default_visibility = ["//visibility:public"])

load("@react_npm//@bazel/typescript:index.bzl", "ts_library")

ts_library(
    name = "config",
    srcs = [":api.config.ts"],
    tsconfig = "//react_app:tsconfig.json",
)